image: gitpod/workspace-full-vnc
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - before: echo y | pyenv install 3.11; pyenv global 3.11
    init: pip3 install -r requirements.txt
    command: python3 icub_pybullet/examples/push_the_ball_pure_joints.py
